import { INITIAL_ATTENDANCE, INITIAL_STORIES, INITIAL_TASKS } from '../data';
import { AttendanceLog, UserStory, Task } from '../types';

export interface ProductivityMetrics {
  totalHoursLogged: number;
  activeEmployeesCount: number;
  completedShiftsCount: number;
  averageShiftHours: number;
  approvedShiftsCount: number;
}

export interface SprintVelocityMetrics {
  totalStoryPoints: number;
  completedStoryPoints: number;
  velocityPercentage: number;
  totalTasksCount: number;
  completedTasksCount: number;
  inProgressTasksCount: number;
  plannedTasksCount: number;
}

export interface GeneratedReport {
  id: string;
  generatedAt: string;
  recipientEmail: string;
  recipientName: string;
  productivity: ProductivityMetrics;
  velocity: SprintVelocityMetrics;
  emailSubject: string;
  emailBodyMarkdown: string;
  deliveryStatus: 'delivered' | 'pending' | 'failed';
}

export function calculateProductivityMetrics(logs: Partial<AttendanceLog>[] = []): ProductivityMetrics {
  const completedLogs = logs.filter((l) => l.status === 'clocked_out');
  const totalHoursLogged = Math.round(
    logs.reduce((acc, l) => acc + (l.totalHours || 0), 0) * 100
  ) / 100;

  const uniqueUsers = new Set(logs.map((l) => l.userId || l.userName)).size;
  const completedShiftsCount = completedLogs.length;
  const averageShiftHours =
    completedShiftsCount > 0
      ? Math.round((totalHoursLogged / completedShiftsCount) * 100) / 100
      : 0;

  const approvedShiftsCount = logs.filter((l) => l.approvalStatus === 'approved').length;

  return {
    totalHoursLogged,
    activeEmployeesCount: uniqueUsers,
    completedShiftsCount,
    averageShiftHours,
    approvedShiftsCount,
  };
}

export function calculateSprintVelocityMetrics(
  stories: Partial<UserStory>[] = [],
  tasks: Partial<Task>[] = []
): SprintVelocityMetrics {
  const totalStoryPoints = stories.reduce((acc, s) => acc + (s.points || 0), 0);
  const completedStoryPoints = stories
    .filter((s) => s.status === 'completed')
    .reduce((acc, s) => acc + (s.points || 0), 0);

  const velocityPercentage =
    totalStoryPoints > 0
      ? Math.round((completedStoryPoints / totalStoryPoints) * 100)
      : 0;

  const totalTasksCount = tasks.length;
  const completedTasksCount = tasks.filter((t) => t.status === 'done').length;
  const inProgressTasksCount = tasks.filter((t) => t.status === 'in_progress' || t.status === 'review').length;
  const plannedTasksCount = tasks.filter((t) => t.status === 'backlog' || t.status === 'todo').length;

  return {
    totalStoryPoints,
    completedStoryPoints,
    velocityPercentage,
    totalTasksCount,
    completedTasksCount,
    inProgressTasksCount,
    plannedTasksCount,
  };
}

export function generateMidnightProductivityReport(
  attendanceLogs: Partial<AttendanceLog>[] = [],
  stories: Partial<UserStory>[] = [],
  tasks: Partial<Task>[] = []
): GeneratedReport {
  const productivity = calculateProductivityMetrics(attendanceLogs);
  const velocity = calculateSprintVelocityMetrics(stories, tasks);
  const nowISO = new Date().toISOString();

  const reportId = `RPT-${Date.now().toString().slice(-6)}`;
  const emailSubject = `[Sahara Agile] Midnight Productivity & Sprint Velocity Report (${nowISO.split('T')[0]})`;

  const emailBodyMarkdown = `
# 📊 Daily Productivity & Sprint Velocity Audit
**Generated:** ${nowISO}  
**Recipient:** Amara Vance (Project Manager - amara.vance@sahara.io)  

---

### ⏱️ Employee Work Hours & Attendance Summary
- **Total Operational Hours Logged:** ${productivity.totalHoursLogged} hrs
- **Active Field Operators:** ${productivity.activeEmployeesCount} engineers
- **Completed Duty Shifts:** ${productivity.completedShiftsCount} shifts
- **Average Shift Duration:** ${productivity.averageShiftHours} hrs / shift
- **Approved Shift Logs:** ${productivity.approvedShiftsCount} verified

### 🚀 Sprint Velocity & Output Metrics
- **Completed Story Points:** ${velocity.completedStoryPoints} / ${velocity.totalStoryPoints} pts (${velocity.velocityPercentage}% velocity rate)
- **Completed Kanban Tasks:** ${velocity.completedTasksCount} / ${velocity.totalTasksCount} tasks
- **Tasks In Progress / Review:** ${velocity.inProgressTasksCount} active items
- **Backlog & Planned Queue:** ${velocity.plannedTasksCount} items remaining

---

*This automated report was generated by the Sahara Agile Redis Job Queue Processor at midnight.*
`;

  return {
    id: reportId,
    generatedAt: nowISO,
    recipientEmail: 'amara.vance@sahara.io',
    recipientName: 'Amara Vance',
    productivity,
    velocity,
    emailSubject,
    emailBodyMarkdown,
    deliveryStatus: 'delivered',
  };
}
